import Header from './components/Header'
import Footer from './components/Footer'
import Breadcrumbs from "./components/Breadcrumbs";
import Bunners from "@/app/components/Bunners";
import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Header/>
        <div>
            <Breadcrumbs/>
            <Bunners/>
            <main>{children}</main>
        </div>
        <Footer/>
        </body>
        </html>
    )
}
